ASoC: Intel: Skylake: Replace modulus operator with div_u64_rem.
Linking errors are observed when compiled for 32 bit architecture as
shown below:

sound/soc/intel/skylake/skl.o: In function `skl_stream_update':
skl.c:(.text+0x213): undefined reference to `__umoddi3'
sound/soc/intel/skylake/skl-probe.o: In function `skl_probe_compr_copy':
skl-probe.c:(.text+0x3f7): undefined reference to `__umoddi3'
skl-probe.c:(.text+0x459): undefined reference to `__umoddi3'

The error for __umoddi3 is observed due to usage of modulus operator on
u64 variable which is unsupported for i386. To fix this, use div_u64_rem
instead.

Change-Id: I3ebba0c28ac50215dc4efff7356a31ba4db930f6
Signed-off-by: Guneshwor Singh <guneshwor.o.singh@intel.com>
Signed-off-by: Dronamraju, Santosh Pavan KumarX <santosh.pavan.kumarx.dronamraju@intel.com>
Reviewed-on:
Reviewed-by: audio_build
Reviewed-by: Prusty, Subhransu S <subhransu.s.prusty@intel.com>
Reviewed-by: Shaik, Kareem M <kareem.m.shaik@intel.com>
Reviewed-by: Tewani, Pradeep D <pradeep.d.tewani@intel.com>
Reviewed-by: Kale, Sanyog R <sanyog.r.kale@intel.com>
Tested-by: Sm, Bhadur A <bhadur.a.sm@intel.com>